name: GPU Price Scraper

on:
  schedule:
      - cron: '0 2 * * *'

jobs:
  scrape:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - uses: actions/setup-python@v4
          with:
            python-version: '3.11'
        - run: python scraper .py
                    
